%\VignetteEngine{knitr::knitr}
\documentclass{article}

\usepackage{graphicx}
\usepackage{microtype}
\usepackage[T1]{fontenc}
\usepackage{float}
\usepackage[latin1]{inputenc}
\usepackage{geometry}
\usepackage{titlesec}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\usepackage[table]{xcolor}
%\newcommand{\sectionbreak}{\clearpage}

\begin{document}

\title{Prognostic Relevance of CD73 and Ovarian Subtypes}

\author{Gregory M. Chen}
\date{\today}
\maketitle

<<setup, include=FALSE, cache=FALSE>>=
# Set options
knitr::opts_chunk$set(include=TRUE, results="hide", fig.width=8, fig.height=8, fig.path='figures/', fig.align='center', fig.show='hold',warning=FALSE, echo=FALSE, message=FALSE, cache=TRUE)
options(replace.assign=TRUE,width=90)
days.per.month <- 30.4368
days.per.year <- 365.242
par.original <- par()
library(gdata)
library(annotate)
library(GSVA)
library(ggplot2)
library(xtable)
library(hgu133plus2.db)
source("../R/getHellandSubtypes.R")
source("../R/create.survival.plot.R")
source("../R/getVerhaakSubtypes.R")
source("../R/getBentinkHaibeKainsSubtypes.R")
source("../R/datasetMerging.R")
source("../R/getSubtype.R")

.getPooledEset <- function(only.hgs=TRUE) {
  if(only.hgs) {
    source("../inst/extdata/hgs.patientselection.config")
  } else {
    source(system.file("extdata", "patientselection.config", package="MetaGxOvarian"))
  }
  source(system.file("extdata", "createEsetList.R", package="MetaGxOvarian"))
  esets <- lapply(esets, function(x) getHellandSubtypes(x)[[1]])
  esets <- lapply(esets, function(x) getVerhaakSubtypes(x)[[1]])
  esets <- lapply(esets, function(x) getBentinkSubtypes(x)[[1]])
  
  esets <- lapply(esets, function(x) {
    factor.indices <- sapply(pData(x), is.factor)
    pData(x)[factor.indices] <- lapply(pData(x)[factor.indices], as.character)
    return(x)
    })
  eset.toreturn <- datasetMerging(esets)
  eset.toreturn$Helland.subtypes <- as.factor(eset.toreturn$Helland.subtypes)
  eset.toreturn$Verhaak.subtypes <- as.factor(eset.toreturn$Verhaak.subtypes)
  eset.toreturn$Bentink.Haibe.Kains.subtypes <- as.factor(eset.toreturn$Bentink.Haibe.Kains.subtypes)
  return(eset.toreturn)
}
@


<<load_data>>=
pooled.eset <- .getPooledEset(only.hgs = TRUE)
@

<<process_data>>=
#for(gene.name in c("NT5E", "CD274", "PDCD1")) {
# Helper function for extracting survival data with quantiles for a given gene.
# The include.sample parameter can be used to specify a subset (e.g. by subtype)
.get.survival.data.for.plotting <- function(eset, gene.name=NULL, entrez.id=NULL, num.quantiles=2, time.unit=c("days", "months", "years"), time.cens=NULL, include.sample=rep(TRUE, nrow(pData(eset)))) {
  time.unit=match.arg(time.unit)
 
  eset <- eset[,include.sample]
  # Find the fData index of the gene 
  if(is.null(gene.name) && is.null(entrez.id)) {
    stop("One of gene.name and entrez.id should be provided")
  }
  if(!is.null(gene.name) && !is.null(entrez.id)) {
    stop("Exactly one of gene.name and entrez.id should be provided")
  }
  if(!is.null(gene.name)) {
    index <- which(fData(eset)$gene == gene.name)
    if(length(index) == 0) {
      warnings(paste("Could not find gene name", gene.name))
      }
    if(length(index) > 1) {
      warning(paste("Found more than one gene called", gene.name))
    }
  }
  if(!is.null(entrez.id)) {
    index <- which(fData(eset)$EntrezGene.ID == entrez.id)
    if(length(index) == 0) {
      warnings(paste("Could not find Entrez ID", entrez.id))
      }
    if(length(index) > 1) {
      warning(paste("Found more than one Entrez ID", entrez.id))
    }
  }
 
  # Get the expression quantile 
  expression.values <- exprs(eset)[index,]
  if(sum(is.na(expression.values)) > 0) {
    message(paste("Found", sum(is.na(expression.values)), "empty gene expression values. Including only the", sum(!is.na(expression.values)), "samples with nonempty values."))
  }
  eset <- eset[,!is.na(expression.values)]
  
  expression.values <- exprs(eset)[index,]
  
  expression.quantiles <- ordered(cut(expression.values, breaks=quantile(expression.values, probs=seq(0,1,length=num.quantiles+1)), include.lowest=TRUE))
  
  if(num.quantiles==2) {
    levels(expression.quantiles) <- c("Low", "High")
  } else if(num.quantiles==3) {
    levels(expression.quantiles) <- c("Low", "Mid", "High")
  } else {
    levels(expression.quantiles) <- paste0("Expression.quantile.", 1:num.quantiles)
  }
  pData(eset) <- cbind(pData(eset), expression.quantiles);
  colnames(pData(eset))[ ncol(pData(eset)) ] <- paste0(gene.name, ".quantile")
  
  survival.data <- pData(eset)[c("data.source", "days_to_death", "vital_status", paste0(gene.name, ".quantile"))]
  
  # only keep cases which has expression values
  survival.data$vital_status <- survival.data$vital_status == "deceased"
  if(time.unit=="months") {
    survival.data$months_to_death <- survival.data$days_to_death / days.per.month
    survival.data$days_to_death <- NULL
    if(!is.null(time.cens)) {
      censored.out <- survcomp::censor.time(survival.data$months_to_death, survival.data$vital_status, time.cens=time.cens)
      survival.data$months_to_death <- censored.out$surv.time.cens
      survival.data$vital_status <- censored.out$surv.event.cens
    }
  }
  if(time.unit=="years") {
    survival.data$years_to_death <- survival.data$days_to_death / days.per.year
    survival.data$days_to_death <- NULL
    if(!is.null(time.cens)) {
      censored.out <- survcomp::censor.time(survival.data$years_to_death, survival.data$vital_status, time.cens=time.cens)
      survival.data$years_to_death <- censored.out$surv.time.cens
      survival.data$vital_status <- censored.out$surv.event.cens
    }
  }
  
  return(survival.data)
}
@

\section{Datasets}

\Sexpr{nrow(pData(pooled.eset))} patients with late-stage, high-grade serous ovarian cancer were pooled from \Sexpr{length(levels(pData(pooled.eset)$data.source))} datasets:
<<Dataset_table, results='asis'>>=
data.counts <- as.data.frame(table(pData(pooled.eset)$data.source))
colnames(data.counts) <- c("Dataset name", "Num samples")
print(xtable(data.counts), include.rownames=FALSE)
@

\section{CD73}

\begin{figure}[H]
<<NT5E_load_data, eval=TRUE, fig.width=6.75, fig.height=8, out.width="0.8\\textwidth">>=
nt5e.survival.data <- .get.survival.data.for.plotting(pooled.eset, gene.name="NT5E", num.quantiles=3, time.unit="years", time.cens=10)
@

All \Sexpr{nrow(nt5e.survival.data)} samples in the pooled dataset had expression levels for CD73. CD73 expression levels were separated into tertiles, and below is a survival curve for the pooled dataset. The p-value is for the likelihood ratio test, and the d- and c-indices were generated by setting risk level concordant with expression level - \textit{i.e.}, higher expression, higher risk.

<<NT5E_survival, eval=TRUE, fig.width=6.75, fig.height=8, out.width="0.8\\textwidth">>=
create.survival.plot(
  surv.time=nt5e.survival.data$years_to_death,
  surv.event=nt5e.survival.data$vital_status,
  groups=nt5e.survival.data$NT5E.quantile,
  xlab="Time (years)",
  reverse.legend.order = TRUE,
  #strata.names=paste("CD73", gsub(".*=", "",levels(nt5e.survival.data$NT5E.quantile))),
  risk.order.same.as.groups=TRUE,
  col=RColorBrewer::brewer.pal(9, name="YlGnBu")[c(4,6,8)]
  )
@
\caption{Survival curves for NT5E tertiles, all subtypes}
\end{figure}

Survival analysis was performed within each ovarian subtype as defined by Tothill et al., 2008 (using our implementation of their group's subtype classifier, described in Helland et al., 2011).
\begin{figure}[H]
<<CD73_survival_tothill_subtypes, eval=TRUE, fig.width=6.75, fig.height=8, out.width="0.6\\textwidth">>=
par(mfrow=c(2,2))
for(x in levels(pooled.eset$Helland.subtypes)) {
  nt5e.subtype.survival.data <- .get.survival.data.for.plotting(pooled.eset, gene.name="NT5E", num.quantiles=3, time.unit="years", time.cens=10, include.sample = pooled.eset$Helland.subtypes == x)
  create.survival.plot(
    surv.time=nt5e.subtype.survival.data$years_to_death,
    surv.event=nt5e.subtype.survival.data$vital_status,
    groups=nt5e.subtype.survival.data$NT5E.quantile,
    xlab="Time (years)",
    main=paste("Survival for subtype", x),
    reverse.legend.order = TRUE,
    #strata.names=paste("CD73", gsub(".*=", "",levels(nt5e.subtype.survival.data$NT5E.quantile))),
    risk.order.same.as.groups=TRUE,
    col=RColorBrewer::brewer.pal(9, name="YlGnBu")[c(4,6,8)]
    )
  }
par(par.original)
@
\caption{Survival curves for CD73 by Tothill subtype}
\end{figure}


Survival analysis was performed within each ovarian subtype as defined by TCGA, 2011 (using our implementation of the subtype classifier described in Verhaak al., 2013).
\begin{figure}[H]
<<CD73_survival_verhaak_subtypes, eval=TRUE, fig.width=6.75, fig.height=8, out.width="0.8\\textwidth">>=
par(mfrow=c(2,2))
for(x in levels(pooled.eset$Verhaak.subtypes)) {
  nt5e.subtype.survival.data <- .get.survival.data.for.plotting(pooled.eset, gene.name="NT5E", num.quantiles=3, time.unit="years", time.cens=10, include.sample = pooled.eset$Verhaak.subtypes == x)
  create.survival.plot(
    surv.time=nt5e.subtype.survival.data$years_to_death,
    surv.event=nt5e.subtype.survival.data$vital_status,
    groups=nt5e.subtype.survival.data$NT5E.quantile,
    xlab="Time (years)",
    main=paste("Survival for subtype", x),
    reverse.legend.order = TRUE,
    #strata.names=paste("CD73", gsub(".*=", "",levels(nt5e.subtype.survival.data$NT5E.quantile))),
    risk.order.same.as.groups=TRUE,
    col=RColorBrewer::brewer.pal(9, name="YlGnBu")[c(4,6,8)]
    )
  }
par(par.original)
@
\caption{Survival curves for CD73 by Verhaak subtype}
\end{figure}


Survival analysis was performed within each ovarian subtype as defined by Bentink et al., 2011 (using the subtype classifier in \texttt{genefu}).
\begin{figure}[H]
<<CD73_survival_bentink_subtypes, eval=TRUE, fig.width=3.375, fig.height=8, out.width="0.8\\textwidth">>=
par(mfrow=c(1,2))
for(x in levels(pooled.eset$Bentink.subtypes)) {
  nt5e.subtype.survival.data <- .get.survival.data.for.plotting(pooled.eset, gene.name="NT5E", num.quantiles=3, time.unit="years", time.cens=10, include.sample = pooled.eset$Bentink.subtypes == x)
  create.survival.plot(
    surv.time=nt5e.subtype.survival.data$years_to_death,
    surv.event=nt5e.subtype.survival.data$vital_status,
    groups=nt5e.subtype.survival.data$NT5E.quantile,
    xlab="Time (years)",
    main=paste("Survival for subtype", x),
    reverse.legend.order = TRUE,
    strata.names=paste("NT5E", gsub(".*=", "",levels(nt5e.subtype.survival.data$NT5E.quantile))),
    risk.order.same.as.groups=TRUE,
    col=RColorBrewer::brewer.pal(9, name="YlGnBu")[c(4,6,8)]
    )
  }
par(par.original)
@
\caption{Survival curves for CD73 by Bentink subtype}
\end{figure}

\end{document}