
#' Function to generate a forest plot in order to visually compare the results form the survival analysis in the individually expression sets
#'
#' This function creates a forest plot for the resulting D indices from using the signature to calculate risk predictions for the patients in multiple datasets
#' @param survInfo One of the data frames in the list returned from the function getPatientSurvivalData. Alternatively, a data frame with 6 columns called eventTime, eventStatus, scoreVals, scoreVals, numGenesPresent, dataName and patient ID that correspond to
#' the survival event times, the survival event's status, the score/risk prediction of the patient, the number of genes used to calculate the score, the name of the dataset that the patient is from and the ID of the patient int that dataset. 
#' @param minPatients an integer specifying the minimum number of patients/samples required to calculate a D.index for one of the datasets. Default is 20. Note that for a dataset with 100 patients and 4 subtypes, something much larger than 20 would 
#' likely remove the D.index in some of the subtype analyses (samples in subtype analysis ~ 100 patients divide 4 subtypes)
#' @param reportSize a boolean indicating whether the size of the plot should be adjusted such that it is the optimal size for the pdf reports generated by createSurvivalReport. By default FALSE, and it should not be set to TRUE as it will likely make seeing the forest plot in R difficult.
#' @return a forest plot with D indices determined by using the signature to calculate risk predictions for the patients in multiple datasets
#' @export
#' @examples
#' 
#' geneEntrezIds = c("43847", "434768", "80070", "3620")
#' geneDirecs = c(1, 1, -1, -1)
#' survInfoList = getPatientSurvivalData(geneEntrezIds, geneDirecs, cancerType = "ovarian", subtype = "verhaak", survivalMetric = "overall")
#' makeForestPlot(survInfoList$`All Patients`)


makeForestPlot = function(survInfo, minPatients = 20, reportSize = FALSE)
{
  forestPlotData = getDindexOfDatasets(survInfo, minPatients)
  remData = unique(which(is.na(forestPlotData), arr.ind = TRUE)[, 1])
  if(length(remData) > 0)
    forestPlotData = forestPlotData[-remData, ]
  if(nrow(forestPlotData) == 0){

  }else{
    dInds = as.numeric(as.character(forestPlotData$dIndex))
    dIndsLow = as.numeric(as.character(forestPlotData$dIndLowerBound))
    dIndsHigh = as.numeric(as.character(forestPlotData$dIndUpperBound))
    dIndsSe = as.numeric(as.character(forestPlotData$dIndStandErr))
    tabText = forestPlotData[ ,-which(grepl("dInd", colnames(forestPlotData)))]
    dindComb = combine.est(dInds, dIndsSe, hetero = TRUE)
    
    meanVec = c(NA, dInds, dindComb$estimate)
    lowerVec = c(NA, dIndsLow, dindComb$estimate - 2*dindComb$se)
    upperVec = c(NA, dIndsHigh, dindComb$estimate + 2*dindComb$se)
    #plotObj = 
    #  structure(list(
    #    mean  = log2(exp(meanVec)), 
    #    lower = log2(exp(lowerVec)),
    #    upper = log2(exp(upperVec))),
    #    .Names = c("mean", "lower", "upper"), 
    #    row.names = c(NA, -(length(dInds) + 2)), 
    #    class = "data.frame")
    plotObj = 
      structure(list(
        mean  = meanVec, 
        lower = lowerVec,
        upper = upperVec),
        .Names = c("mean", "lower", "upper"), 
        row.names = c(NA, -(length(dInds) + 2)), 
        class = "data.frame")
    
    
    tabletext<-cbind(
      c("Study", as.character(tabText[,1]), "Summary"),
      c("Patients", as.character(tabText[,2]), NA),
      c("# Genes Present", as.character(tabText[,3]), NA),
      c("D Index", as.character(format(dInds, digits = 2)), as.character(format(dindComb$estimate, digits = 2)))) 
    
    if(reportSize == TRUE){
      forestplot(tabletext, plotObj, is.summary=c(TRUE,rep(FALSE,length(dInds)),TRUE), 
                 col=fpColors(box="royalblue",line="darkblue", summary="royalblue"), clip=c(0.1,2.5), line.margin = .15,
                 boxsize = 0.25, cex = 1.5, txt_gp = fpTxtGp(label = list(ticks = gpar(fontfamily = "", cex=1.5))), 
                 lineheight = unit(2, "cm"), xlab="D index", zero = 1)
      
    }else{
      
      #par(mar=c(4,4,1,2))
      par(font=1)
      
      metaforText = tabletext[-c(1, nrow(tabletext)), ]
      metaforText = rbind(metaforText, c("Meta D Index", "", "", as.character(format(dindComb$estimate, digits = 2))))
      
      metaforPlotObj = plotObj[-c(1), ]
      
      forest(x = log2(metaforPlotObj$mean), ci.lb = log2(metaforPlotObj$lower), ci.ub = log2(metaforPlotObj$upper), at=seq(-2,2), digits=1, xlim=c(-23,9),
             ilab=metaforText[, -1],ilab.xpos=c(-15,-10,-6), rows=c(1:(nrow(metaforText)-1),-3),
             xlab="log2(D Index)", mlab="", psize=1, ylim = c(-3, nrow(metaforText) + 3), slab = metaforText[(1:nrow(metaforPlotObj)),1])
      
      op <- par(cex=.9, font=4)
      par(font=2)
      
      ### add column headings to the plot
      text(c(-15,-10,-6), nrow(metaforText) + 2, c("Patients", "# Genes", "D Index"))
      text(-23,                nrow(metaforText) + 2, "Study",  pos=4)
      text(9,                  nrow(metaforText) + 2, "log2(D Index)[95% CI]", pos=2)
      
      #forestplot(tabletext, 
      #           plotObj,
      #           is.summary=c(TRUE,rep(FALSE,length(dInds)),TRUE),
      #           clip=c(0,5),
      #           col=fpColors(box="royalblue",line="darkblue", summary="royalblue"), zero = 1) 
    } 
  }

}
